# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-02 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='shop',
            name='owner',
            field=models.CharField(default='\u0412\u043b\u0430\u0434\u0435\u043b\u0435\u0446', max_length=255, verbose_name='\u0412\u043b\u0430\u0434\u0435\u043b\u0435\u0446'),
        ),
    ]
