# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20160408_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='first_name',
            new_name='owner_name',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='last_name',
        ),
    ]
