# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20160408_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='owner_name',
            field=models.CharField(max_length=255, verbose_name='\u0418\u043c\u044f'),
        ),
    ]
