# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-02 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static/probuct.jpg', upload_to=b''),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='\u041d\u0430\u0441\u0432\u0430\u043d\u0438\u0435 \u0442\u043e\u0432\u0430\u0440\u0430', max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0442\u043e\u0432\u0430\u0440\u0430'),
        ),
    ]
