# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20160405_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u0442\u044c'),
        ),
    ]
