# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20160417_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='product.Product'),
        ),
    ]
