# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-07 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='\u041e\u0442\u0437\u044b\u0432')),
            ],
        ),
    ]
